# Generated by Django 5.2.6 on 2025-10-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='normalized_communications',
            field=models.FloatField(blank=True, help_text='Normalized Q3.12_5 (-1 to 1)', null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='normalized_confidence',
            field=models.FloatField(blank=True, help_text='Normalized Q3.11 (-1 to 1)', null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='normalized_expectations',
            field=models.FloatField(blank=True, help_text='Normalized Q3.12_6 (-1 to 1)', null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='normalized_hard_skills',
            field=models.FloatField(blank=True, help_text='Normalized Q3.9 (-1 to 1)', null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='normalized_initiation',
            field=models.FloatField(blank=True, help_text='Normalized Q3.12_2 (-1 to 1)', null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='normalized_mentorship',
            field=models.FloatField(blank=True, help_text='Normalized Q3.12_3 (-1 to 1)', null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='normalized_onboarding',
            field=models.FloatField(blank=True, help_text='Normalized Q3.12_1 (-1 to 1)', null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='normalized_soft_skills',
            field=models.FloatField(blank=True, help_text='Normalized Q3.10 (-1 to 1)', null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='normalized_sponsor',
            field=models.FloatField(blank=True, help_text='Normalized Q3.12_7 (-1 to 1)', null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='normalized_team',
            field=models.FloatField(blank=True, help_text='Normalized Q3.12_4 (-1 to 1)', null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='normalized_workload',
            field=models.FloatField(blank=True, help_text='Normalized Q3.12_8 (-1 to 1)', null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='project_mentor',
            field=models.CharField(blank=True, help_text='Mapped mentor name from mentor_choice', max_length=200),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='topic',
            field=models.CharField(blank=True, help_text='Mapped topic name from topics_working_on or topics_worked_on', max_length=200),
        ),
    ]
